# ==========================================
# CONFIGURAÇÕES DA APLICAÇÃO E PORTA
# ==========================================
server.port=8080
spring.application.name=analytics-api

# ==========================================
# CONFIGURAÇÕES DO BANCO DE DADOS H2
# ==========================================
spring.datasource.url=jdbc:h2:mem:growthdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilitar o Console Web do H2 (Acesso visual ao banco)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# JPA / HIBERNATE (Tradutor de Java para SQL)
# ==========================================
# Cria e atualiza as tabelas automaticamente baseado nas nossas classes Java
spring.jpa.hibernate.ddl-auto=update
# Exibe os comandos SQL no terminal para acompanharmos o motor trabalhando
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ==========================================
# SWAGGER / OPENAPI (Documentação Visual)
# ==========================================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html